### ISSUE TITLE
VPC Gen 2

### ISSUE THREAD

**Issue by movinglightspeed** [IBM/vpc-go-sdk#11]
I saw on the overview page
Service Name | Package name
-- | --
VPC | vpcv1
VPC Gen 1 | vpcclassicv1

When will VPC Gen 2 be supported? 

Some features like block storage for Gen 2 can't use BYOK because its depended on this SDK being updated"
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1673#issuecomment-670401620

**Comment by astha-jain** [comment]
hi. vpcv1 is Gen2

**Comment by movinglightspeed** [comment]
Thank you for that clarification. @astha-jain I meant VPC Gen 2 BYOK feature update.

"We are waiting for the SDK to update the BYOK feature for Gen2
https://github.com/IBM/vpc-go-sdk/

Once we have the SDK rolled out with this feature we will support for Gen2 also"

**Comment by astha-jain** [comment]
https://github.com/IBM/vpc-go-sdk/releases/tag/v0.0.3 supports BYOK for gen 2.

**Comment by movinglightspeed** [comment]
The terraform team is waiting for the SDK to update, any idea when this will be?
