### ISSUE TITLE
Provider pointer helpers

### ISSUE THREAD

**Issue by srowles** [IBM/vpc-go-sdk#7]
The AWS SDK does this, because most types require a pointer (e.g. pointer to string, pointer to bool etc) please provider simple helper methods e.g.

```
func String(value string) *string {
   return &value
}

func Bool(value bool) *bool {
    return &value
}
```

etc.

It would also be really useful to have simple helpers for "safe" values e.g.

```
func SafeString(ptr *string, default string) string {
    if ptr == nil {
        return default
    }

    return *ptr
}
```

**Comment by mkistler** [comment]
The IBM Go SDK Core, which underlies the VPC Go SDK, provides these helpers, e.g. [StringPtr](https://github.com/IBM/go-sdk-core/blob/0117461d47c1a734c8726ecfe4ad5cbd1c971af2/v4/core/utils.go#L82)
```
// StringPtr returns a pointer to string literal.
func StringPtr(literal string) *string {
	return &literal
}
```

"Safe" helpers are not provided but could be added with sufficient justification.  Can you provide this?

**Comment by srowles** [comment]
Thank you for the info. For the "safe" helpers I am often extracting information about vpc objects for display or reference, I don't care what the values are and so, for example, blank string is fine if the value is nil, and avoid me having to handle the nil.

I also sometimes need to extract a value from deep in a structure which might contain nil in the path. Using the softlayer-go library I use this:

https://github.com/softlayer/softlayer-go/blob/master/sl/helpers.go#L143

It would be really useful to have that function, and the OK variant, available in the core go SDK as well. The usage would be, for example, that I want to get a network interface IP address, the Grab method let's me easily get the value, or blank if there is a nil structure somewhere in the hierarchy.

I'd be happy to port and create the helpers and submit and MR

**Comment by mkistler** [comment]
We welcome community contributions!

The "safe" variants seem like they are useful for users, but less so for the SDK itself, which I think explains why these were not included in the Go Core SDK.
