### ISSUE TITLE
Package confusion

### ISSUE THREAD

**Issue by saracen** [IBM/vpc-go-sdk#73]
Hey, this might not be the best place to ask (please let me know if there's a more suitable place).

- Should this not be under the `IBM-Cloud` namespace, like https://github.com/IBM-Cloud/power-go-client is? If not, I'm curious as to the reason.
- Are there any plans for VPC to support Power Systems? It feels odd that there's a completely separate API.

**Comment by astha-jain** [comment]
Hey there! @saracen. To answer your questions - 
- SDKs are available across both namespaces. 
- Here is a note of Power Systems from June 2020 I could find https://cloud.ibm.com/docs/vpc?topic=vpc-release-notes#vpc-jun0220
